-- Fix profiles table
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;
ALTER TABLE profiles ALTER COLUMN id DROP NOT NULL;
ALTER TABLE profiles ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- Fix all other tables with similar issues
ALTER TABLE sales ALTER COLUMN id DROP NOT NULL;
ALTER TABLE sales ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE products ALTER COLUMN id DROP NOT NULL;
ALTER TABLE products ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE projects ALTER COLUMN id DROP NOT NULL;
ALTER TABLE projects ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE invoices ALTER COLUMN id DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE notifications ALTER COLUMN id DROP NOT NULL;
ALTER TABLE notifications ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE leads ALTER COLUMN id DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE ideas ALTER COLUMN id DROP NOT NULL;
ALTER TABLE ideas ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE sources ALTER COLUMN id DROP NOT NULL;
ALTER TABLE sources ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE campaigns ALTER COLUMN id DROP NOT NULL;
ALTER TABLE campaigns ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- Disable RLS for all tables
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE ideas DISABLE ROW LEVEL SECURITY;
ALTER TABLE sources DISABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns DISABLE ROW LEVEL SECURITY;
